language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

notifications:
  email:
    - helmut@typo3.org

sudo: false

cache:
  directories:
    - $HOME/.composer

before_script:
  - composer self-update
  - composer install
  - cat test.php

script:
  - php test.php