language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6

notifications:
  email:
    - helmut@typo3.org

sudo: false

cache:
  directories:
    - $HOME/.composer
    - $HOME/.phpenv/bin

before_script:
  - \[ -f "$HOME/.phpenv/bin/parallel" \] || wget http://git.savannah.gnu.org/cgit/parallel.git/plain/src/parallel && mv parallel $HOME/.phpenv/bin/ && chmod 755 $HOME/.phpenv/bin/parallel
  - parallel --help
  - composer self-update
  - composer install
  - cat test.php

script:
  - php test.php
